### ISSUE TITLE
Circle CI returns a fail

### ISSUE THREAD

**Issue by Abdallahassan** [Abdallahassan/zulip#6]
The current code gives some kind of pipefail on Circle CI, you can see it in the last push or if you do a new push yourself, even though Travis CI gives no fails or error. I think this should be looked into because the zulip project automatically runs Circle CI for every pull request, and I don't think they'll accept our contribution if any tests fail.

**Comment by ZiadP** [comment]
Waiting to see if this fixed the error and passed tests. It seems like this is already done in  zulip git. Weird that it's missing from ours.

**Comment by ZiadP** [comment]
It seemed to work, maybe we should pull down latest code from zulip.
